spring:
  application:
    name: contrato-espaco
  
  datasource:
    url: jdbc:postgresql://ep-weathered-salad-a5vgz2iq-pooler.us-east-2.aws.neon.tech:5432/neondb
    username: neondb_owner
    password: npg_8wKSN7HUXuOF
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never
      # schema-locations: classpath:schema.sql
      # data-locations: classpath:data.sql
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /api

# Configurações de Debug
debug: true

logging:
  level:
    '[com.atom.contratoespaco]': DEBUG
    '[org.springframework.web]': DEBUG
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE

'[management]':
  '[endpoints]':
    '[web]':
      '[exposure]':
        '[include]': health,info,metrics
